const actionType ={
    UPDATE_YOUR_INFO:'UPDATE_YOUR_INFO',
    UPDATE_PERIOD:'UPDATE_PERIOD',
    UPDATE_PLAN:'UPDATE_PLAN',
    UPDATE_ADDONS:'UPDATE_ADDONS',
    RESET:'RESET',
}
export default actionType;